### ISSUE TITLE
Index is not determined by metric's timestamp when writing.

### ISSUE THREAD

**Issue by jerome89** [graphene-monitoring/graphene#17]
Currently there's an issue when system tries to write metric with TimeBased rolling strategy.
When system tries to write metric key on Elasticsearch with TimeBased rolling strategy, the index is not determined by received metric's timestamp. I've checked the code and found that the system decides which index to be written by just using system's current time.
This is major bug because the value is stored in C* with received timestamp, and this does not match with key storage's index. Users will not be able to search key in this case.

**Comment by Dark0096** [comment]
Thanks. The first architecture had only supported the time series metric based on the current time.
I think it's better if Graphene supports historical data. It is possible to analyze previous data through various functions and to help operate the metric system stably through data recovery.

Please check below for details:
https://github.com/graphene-monitoring/graphene/pull/18
