### ISSUE TITLE
Cannot read and write metric key from ES.

### ISSUE THREAD

**Issue by jerome89** [graphene-monitoring/graphene#33]
As the new year approaches, Graphene tries to create the first week index of the new year. The issue occurs here. System created w1 index when check its existence but all the indexing and search requests are going to w01, which leads to throw 'index_not_found_index' exception. Seems the number of digit occurs the problem here.

**Comment by Dark0096** [comment]
Thank you. 
This issue was resolved.

Please see that you want to check the resolved code: #34
