### ISSUE TITLE
The code to normalize the timestamp is scattered all over the code.

### ISSUE THREAD

**Issue by Dark0096** [graphene-monitoring/graphene#47]
The code to normalize the timestamp is scattered all over the code. 
Accordingly, it is likely that time information is incorrectly stored for each metric source like GRAPHITE, PROMETHEUS, INFLUXDB. It seems necessary to keep it consistent by modifying it in one place.

**Comment by jerome89** [comment]
This will be handled by each data store handlers, work is in progress in ```feature/configurable-resolution``` branch. Thanks for reporting.
