### ISSUE TITLE
An auto-complete feature is not available in some cases.

### ISSUE THREAD

**Issue by Dark0096** [graphene-monitoring/graphene#53]
He who is @ (@hwanjin-jeong) said :
An auto-complete feature is not available in some cases.
For example) If I want to find the middle word, Bytes, It's impossible.

![image](https://user-images.githubusercontent.com/1639208/73624531-889f7380-4684-11ea-99f8-c2dfbd295e95.png)

**Comment by jerome89** [comment]
This issue is resolved in https://github.com/graphene-monitoring/graphene/pull/69 .
