### ISSUE TITLE
support REST API?

### ISSUE THREAD

**Issue by rulejj** [graphene-monitoring/graphene#76]
Hello?
I'm using graphene useful! Thank you.
I have one suggestion.
When I put data into graphene, I use socket (using netcat, python, etc.) to put the data.
It's not inconvenient, but I think it's more comfortable to use the REST API.
Do you have any plans to support the http protocol?

For reference, I am using a simple converter like this:
Thank you.

```
import time
import socket

M_WRITER_ENDPOINT = 'host'
M_WRITER_PORT = 9880

def send_to_metricstore(points):
    client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    client.connect((M_WRITER_ENDPOINT, M_WRITER_PORT))
    client.send(points.encode())
    client.close()

def main(args):
    try:
        cur_ts = int(time.time())
        key = args.get("key")
        value = args.get("value")
        ts = args.get("ts")
        if ts == "" :
            ts = str(cur_ts)
        payload = key + " " + value + " " + ts + "\n"
        send_to_metricstore(payload)
        
        return {"payload": payload, "ts": cur_ts}
    except Exception as e:
        return {"error": str(e)}

# curl -Ss "http://somwhere/graphene?key=${key}&value=${value}&ts=${timestamp}"
```

**Comment by Dark0096** [comment]
Hello~! :)

Graphene exposed a http endpoint for influxdb support.
```
$ curl -i -XPOST "http://localhost/write?db=mydb&precision=s" --data-binary 'cpu,hostname=localhost cpu_user=90 1463683075'
```
( https://docs.influxdata.com/influxdb/v1.8/tools/api/#write-http-endpoint )

Thanks for your suggestion.

**Comment by rulejj** [comment]
@Dark0096 
That is what I want.
Thank you for your guidance.

**Comment by Dark0096** [comment]
Glad I could help :)
